#!/bin/bash
SDCARD="/media/kasmir/SD/DCIM"

rsync --verbose --progress --stats --recursive --ignore-existing --times $SDCARD/100CANON/*.CR2 $SDCARD/100CANON/*.MOV $SDCARD/101CANON/*.CR2 $SDCARD/101CANON/*.MOV $SDCARD/102CANON/*.CR2 $SDCARD/102CANON/*.MOV ./Temp/

rsync --verbose --progress --stats --recursive --ignore-existing --times $SDCARD/100CANON/*.CR2 $SDCARD/100CANON/*.MOV $SDCARD/101CANON/*.CR2 $SDCARD/101CANON/*.MOV $SDCARD/102CANON/*.CR2 $SDCARD/102CANON/*.MOV ./Temp2/

SDCARD="/media/kasmir/C92A-4200/DCIM"

rsync --verbose --progress --stats --recursive --ignore-existing --times $SDCARD/100CANON/*.CR2 $SDCARD/100CANON/*.MOV $SDCARD/101CANON/*.CR2 $SDCARD/101CANON/*.MOV $SDCARD/102CANON/*.CR2 $SDCARD/102CANON/*.MOV ./Temp/

rsync --verbose --progress --stats --recursive --ignore-existing --times $SDCARD/100CANON/*.CR2 $SDCARD/100CANON/*.MOV $SDCARD/101CANON/*.CR2 $SDCARD/101CANON/*.MOV $SDCARD/102CANON/*.CR2 $SDCARD/102CANON/*.MOV ./Temp2/

python ./renamefiles.py ./Temp/
python ./renamefiles.py ./Temp2/
